// bin2cpp — build-time host tool that embeds a binary file as a C++ source.
//
// Reads an input binary and writes a C++ translation unit defining its bytes as
// a named array with external linkage in namespace Veng, plus a `<symbol>Size`
// byte count. Replaces the CMake byte-loop embedder, whose per-byte string
// building was quadratic and crawled on multi-megabyte packs.
//
//   bin2cpp <input> <output> <symbol>

#include <cstdio>
#include <filesystem>
#include <string>
#include <vector>

namespace
{

    constexpr char HexDigits[] = "0123456789abcdef";

    // Bytes emitted per line in the generated array initializer.
    constexpr int BytesPerLine = 16;

    std::vector<unsigned char> ReadFile(const char* path)
    {
        std::FILE* file = std::fopen(path, "rb");
        if (file == nullptr)
        {
            std::fprintf(stderr, "bin2cpp: cannot open input '%s'\n", path);
            std::exit(1);
        }

        std::fseek(file, 0, SEEK_END);
        const long size = std::ftell(file);
        std::rewind(file);

        std::vector<unsigned char> bytes(static_cast<std::size_t>(size));
        if (size > 0 && std::fread(bytes.data(), 1, bytes.size(), file) != bytes.size())
        {
            std::fprintf(stderr, "bin2cpp: short read on '%s'\n", path);
            std::exit(1);
        }
        std::fclose(file);
        return bytes;
    }

} // namespace

int main(int argc, char** argv)
{
    if (argc != 4)
    {
        std::fprintf(stderr, "usage: bin2cpp <input> <output> <symbol>\n");
        return 1;
    }

    const char* inputPath = argv[1];
    const char* outputPath = argv[2];
    const char* symbol = argv[3];

    const std::vector<unsigned char> bytes = ReadFile(inputPath);

    // Build the whole source in memory and write it in one pass; per-byte stdio
    // would dominate the runtime on a large pack.
    std::string out;
    out.reserve(bytes.size() * 6 + 256);

    out += "// Auto-generated by cmake/bin2cpp.cpp — do not edit.\n";
    out += "namespace Veng {\n";
    out += "extern const unsigned char ";
    out += symbol;
    out += "[] = {\n";

    for (std::size_t i = 0; i < bytes.size(); ++i)
    {
        if (i % BytesPerLine == 0)
        {
            out += "    ";
        }

        const unsigned char byte = bytes[i];
        out += "0x";
        out += HexDigits[byte >> 4];
        out += HexDigits[byte & 0x0F];

        if (i + 1 != bytes.size())
        {
            out += ',';
        }

        const bool endOfLine = (i % BytesPerLine == BytesPerLine - 1) || (i + 1 == bytes.size());
        out += endOfLine ? '\n' : ' ';
    }

    out += "};\n";
    out += "extern const unsigned long ";
    out += symbol;
    out += "Size = ";
    out += std::to_string(bytes.size());
    out += ";\n}\n";

    const std::filesystem::path outputFile{outputPath};
    if (outputFile.has_parent_path())
    {
        std::error_code ec;
        std::filesystem::create_directories(outputFile.parent_path(), ec);
    }

    std::FILE* file = std::fopen(outputPath, "wb");
    if (file == nullptr)
    {
        std::fprintf(stderr, "bin2cpp: cannot open output '%s'\n", outputPath);
        return 1;
    }
    std::fwrite(out.data(), 1, out.size(), file);
    std::fclose(file);

    std::printf("bin2cpp: wrote %zu bytes as %s -> %s\n", bytes.size(), symbol, outputPath);
    return 0;
}
