# cmake/EmbedBinary.cmake — invoked as a cmake -P script.
# Reads INPUT binary, writes a C++ source to OUTPUT that defines the bytes
# as a named array (SYMBOL) with external linkage in namespace Veng.
#
# Usage:
#   cmake -DINPUT=<bin> -DOUTPUT=<cpp> -DSYMBOL=<name> -P EmbedBinary.cmake

if (NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOL)
    message(FATAL_ERROR "EmbedBinary: INPUT, OUTPUT, and SYMBOL must be defined.")
endif ()

file(READ "${INPUT}" hex HEX)

string(LENGTH "${hex}" hexLen)
math(EXPR byteCount "${hexLen} / 2")

# Build the comma-separated byte list, 16 bytes per line.
set(byteList "")
set(col 0)
math(EXPR lastByte "${byteCount} - 1")

foreach (i RANGE 0 ${lastByte})
    math(EXPR hexOff "${i} * 2")
    string(SUBSTRING "${hex}" ${hexOff} 2 byteHex)

    if (col EQUAL 0)
        string(APPEND byteList "    ")
    endif ()

    string(APPEND byteList "0x${byteHex}")

    if (NOT i EQUAL ${lastByte})
        string(APPEND byteList ",")
    endif ()

    math(EXPR col "${col} + 1")
    if (col EQUAL 16 AND NOT i EQUAL ${lastByte})
        string(APPEND byteList "\n")
        set(col 0)
    elseif (NOT col EQUAL 16)
        string(APPEND byteList " ")
    endif ()
endforeach ()

set(content
"// Auto-generated by cmake/EmbedBinary.cmake — do not edit.
namespace Veng {
extern const unsigned char ${SYMBOL}[] = {
${byteList}
};
extern const unsigned long ${SYMBOL}Size = ${byteCount};
}
")

# Ensure output directory exists.
get_filename_component(outDir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${outDir}")

file(WRITE "${OUTPUT}" "${content}")
message(STATUS "EmbedBinary: wrote ${byteCount} bytes as ${SYMBOL} -> ${OUTPUT}")
